apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
data:
  backup-script.sh: |
    #!/bin/bash

    MONGO_HOST="mongo.default.svc.cluster.local"
    BACKUP_DIR="/backup"

    TIMESTAMP=$(date +%Y%m%d%H%M%S)
    BACKUP_FILE="$BACKUP_DIR/backup-$TIMESTAMP.tar.gz"

    mongodump --host $MONGO_HOST --gzip --archive=$BACKUP_FILE

    if [ $? -eq 0 ]; then
      echo "Backup successful"
    else
      echo "Backup failed"
    fi