apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup-pv
spec:
  capacity:
    storage: 10Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # Change this based on your storage class
  hostPath:
    path: /data/db 