apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup-pv
spec:
  capacity:
    storage: 10Gi  
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  
  hostPath:
    path: /data/db 
